---
- name: Setup Vprofile Bastion hosts
  hosts: localhost
  connection: local
  gather_facts: no 
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/bastion_setup


    - name: Import VPC setup Variable
      include_vars: vars/output_vars


