---
- name: Setup Vprofile Bastion hosts
  hosts: localhost
  connection: local
  gather_facts: no 
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/vpc_setup


    - name: Import VPC setup Variable
      include_vars: vars/output_vars

    - name: Create bastion host ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{ region }}"
      register: vprofile_key_out

    - name: Create sec Grp for bastion host
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out      

    - name: Creating Bastion host  
      ec2: 
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          Project: Vprofile
          Owner: Devops Team
        exact_count: 1
        count_tag:
           Name: "Bastion_host"
           Project: Vprofile
           Owner: Devops Team
        group_id: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out





      


