- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup
    - name: Create vprofile VPC
      ec2_vpc_net: 
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCider}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: yes
        state: "{{state}}"
      register: vpcout
