---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC setup Variables
      include_vars: vars/output_vars

    - name: Import vprofile setup Variable
      include_vars: vars/vprostacksetup

    - name: Create vprofile ec2 key
      ec2_key:
        name: vpro_key
        region: "{{region}}"
      register: vpro_key_out

    - name: Save private key into file loginkey_vpro.pem
      copy: 
        content: "{{vpro_key_out.private_key}}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vpro_key_out.changed
